# Generated by Django 5.2.8 on 2025-12-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_featuredproject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects_img/')),
                ('tech', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('github_link', models.URLField(blank=True, max_length=500)),
                ('live_link', models.URLField(blank=True, max_length=500)),
                ('other_link', models.URLField(blank=True, max_length=500)),
                ('type', models.CharField(choices=[('featured', 'Featured'), ('other', 'Other')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FeaturedProject',
        ),
    ]
