# Generated by Django 5.2.8 on 2025-12-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_delete_featuredproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
    ]
