# Generated by Django 5.2.8 on 2025-12-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techoffer',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='techoffer',
            old_name='Icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='techoffer',
            old_name='Status',
            new_name='status',
        ),
    ]
